development:
  adapter: postgresql
  encoding: utf8
  database: baseball_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: baseball_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: baseball_production
  pool: 5
  username:
  password:
